### ISSUE TITLE
Document ci-server GH usage with(in) espressif/idf:xx containers

### ISSUE THREAD

**Issue by petermm** [wokwi/wokwi-ci-server-action#1]
Previously we (AtomVM) struggled using `wokwi-ci-server-action` in GH actions as we are using the espressif/idf:XY containers and you end up doing docker inside docker, to no avail.

turns out one can easily use the `services` method https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/about-service-containers

```
     container: espressif/idf:${{ matrix.idf-version }}
     services:
       wokwi-ci-server:
         image: wokwi/wokwi-ci-server
         ports:
           - 3000:3000
```

and before running pytest

```
      - name: Configure Wokwi environment
         run: |
           echo "WOKWI_CLI_SERVER=ws://wokwi-ci-server:3000" >> $GITHUB_ENV
```

So I suggest documenting and supporting that.
